// <auto-generated />
using System;
using BabyCareAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BabyCareAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(BabyCareAssistantDbContext))]
    [Migration("20260214040036_FixMissingColumns")]
    partial class FixMissingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.Baby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Babies");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.ExcretionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.ToTable("ExcretionLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExcretionLogs_Type", "\"Type\" IN ('Wet', 'Dirty', 'Mixed')");
                        });
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FamilyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.FeedingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountMl")
                        .HasColumnType("integer");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FeedingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LeftBreastDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("RightBreastDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.ToTable("FeedingLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeedingLogs_Type", "\"Type\" IN ('Bottle', 'Breast', 'Solids')");
                        });
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.GrowthLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateMeasured")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HeadCircumferenceCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.ToTable("GrowthLogs", (string)null);
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CognitoSubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSubjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.VaccinationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdministeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VaccineCatalogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.HasIndex("VaccineCatalogId");

                    b.ToTable("VaccinationRecords", (string)null);
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.VaccineCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DueAtMonths")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VaccineCatalog", (string)null);
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.Baby", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Family", null)
                        .WithMany("Babies")
                        .HasForeignKey("FamilyId");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.ExcretionLog", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Baby", "Baby")
                        .WithMany("ExcretionLogs")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BabyCareAssistant.Domain.Entities.User", "User")
                        .WithMany("FamilyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.FeedingLog", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Baby", "Baby")
                        .WithMany("FeedingLogs")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.GrowthLog", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Baby", "Baby")
                        .WithMany("GrowthLogs")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.VaccinationRecord", b =>
                {
                    b.HasOne("BabyCareAssistant.Domain.Entities.Baby", "Baby")
                        .WithMany("VaccinationRecords")
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BabyCareAssistant.Domain.Entities.VaccineCatalog", "VaccineCatalog")
                        .WithMany("Records")
                        .HasForeignKey("VaccineCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Baby");

                    b.Navigation("VaccineCatalog");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.Baby", b =>
                {
                    b.Navigation("ExcretionLogs");

                    b.Navigation("FeedingLogs");

                    b.Navigation("GrowthLogs");

                    b.Navigation("VaccinationRecords");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.Family", b =>
                {
                    b.Navigation("Babies");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.User", b =>
                {
                    b.Navigation("FamilyMemberships");
                });

            modelBuilder.Entity("BabyCareAssistant.Domain.Entities.VaccineCatalog", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
