<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>8aacd240-f68f-42fa-a170-1575e0a4a60c</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BabyCareAssistant.Application\BabyCareAssistant.Application.csproj" />
      <ProjectReference Include="..\BabyCareAssistant.Infrastructure\BabyCareAssistant.Infrastructure.csproj" />
      <ProjectReference Include="..\BabyCareAssistant.Domain\BabyCareAssistant.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Repositories\" />
    </ItemGroup>

</Project>
