<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BabyCareAssistant.Application\BabyCareAssistant.Application.csproj" />
    <ProjectReference Include="..\BabyCareAssistant.Domain\BabyCareAssistant.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.15" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.23" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
